---
- name:
  user:
    name: "{{sname}}"
    password: "{{'Abc123' | password_hash('sha512') }}"
    comment: "{{sfull}}"
    shell: /bin/bash
    group: wheel
    grous: wheel
    home: /home/{{sname}}
